# Generated by Django 5.0.1 on 2024-01-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='comments',
            field=models.CharField(default='....', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='documents',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
