# Generated by Django 5.0.1 on 2024-01-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_alter_documents_comments_alter_documents_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ocr_app.userprofile'),
        ),
    ]
